# Generated by Django 6.0.3 on 2026-06-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_customuser_password1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={},
        ),
        migrations.AddField(
            model_name="address",
            name="phone_number",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
