# Generated by Django 6.0.3 on 2026-06-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="address_line1",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="address_line2",
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
    ]
