# Generated by Django 6.0.3 on 2026-06-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_address_line1_order_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
