# Generated by Django 6.0.3 on 2026-06-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_shipping_charge_order_subtotal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="discount_percentage",
            new_name="discount",
        ),
        migrations.AddField(
            model_name="coupon",
            name="coupon_type",
            field=models.CharField(
                choices=[("percentage", "Percentage"), ("fixed", "Fixed Amount")],
                default="percentage",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="minimum_order_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="coupon",
            name="used_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
