# Generated by Django 6.0.3 on 2026-06-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_rename_discount_percentage_coupon_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
