# Generated by Django 6.0.3 on 2026-04-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productsize_product_alter_variant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='value',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='value',
            field=models.CharField(choices=[('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9')], max_length=20),
        ),
    ]
