# Generated by Django 6.0.3 on 2026-04-02 07:19

import autoslug.fields
import products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productcolor_value_alter_productsize_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=products.models.Category.generate_slug, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=products.models.Product.generate_slug, unique=True),
        ),
    ]
