# Generated by Django 6.0.3 on 2026-04-11 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productsize_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='products.productsize'),
        ),
    ]
