# Generated by Django 6.0.3 on 2026-04-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productcolor_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['product', 'size']},
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'size')},
        ),
        migrations.RemoveField(
            model_name='variant',
            name='color',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
