# Generated by Django 6.0.3 on 2026-04-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_variant_options_alter_variant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
