# Generated by Django 6.0.3 on 2026-05-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(choices=[('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9')], max_length=20),
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['size']},
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
